runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /fonts
  static_dir: fonts
- url: /favicon.ico
  static_files: favicon.png
  upload: favicon.png
- url: /.*
  script: templates.app

libraries:
- name: jinja2
  version: latest
